# volumes:
volumes:
  recipe-db:
    external: true

services:
  fastapi:
    environment:
      CORS_HOST: http://localhost:3000
      DATABASE_URL: postgresql://user:secret@postgres/recipe-db
      SIGNING_KEY: ey98119cb2df992b3bcb108de1174f3d45606402ee655ca7222572a8ed81f3fcf4
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
      DATABASE_URL: postgresql://user:secret@postgres/recipe-db



  postgres:
      image: postgres:14.5-bullseye
      volumes:
          - recipe-db:/var/lib/postgresql/data
      environment:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: user
          POSTGRES_DB: recipe-db
      ports:
            - 15432:5432